import { Logo } from '@ost-cas-fee-adv-23-24/design-system-component-library-team-batman';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
const font = Poppins({
  variable: '--font-poppins',
  weight: ['500', '600', '700'],
  subsets: ['latin-ext'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <nav className="bg-primary-600">
          <Logo variant="white" />
        </nav>
        {children}
      </body>
    </html>
  );
}
