name: 🐼 PROD-WORKFLOW
on:
  push:
    branches: [main]

jobs:
  verify:
    uses: ./.github/workflows/task-verify-code.yml
    secrets: inherit

  deploy-preview:
    needs: verify
    uses: ./.github/workflows/task-deploy.yml
    with:
      VARIANT: 'PREVIEW'
    secrets: inherit

  e2e:
    needs: deploy-preview
    uses: ./.github/workflows/task-e2e.yml
    with:
      DEPLOY_URL: ${{ needs.deploy-preview.outputs.DEPLOY_URL }}
    secrets: inherit

  lighthouse:
    needs: deploy-preview
    uses: ./.github/workflows/task-lighthouse.yml
    with:
      DEPLOY_URL: ${{ needs.deploy-preview.outputs.DEPLOY_URL }}
      VARIANT: 'PROD'
    secrets: inherit

  deploy-prod:
    needs: e2e
    uses: ./.github/workflows/task-deploy.yml
    with:
      VARIANT: 'PROD'
    secrets: inherit
